name: CI

on:
  [push] # triggers pipeline when a push is made do any branch in this repo
  #push: triggers when there is a push in a here specified branch
  #  branches:
  #   - main
jobs:
    # SAST drop/scan
    # Security Application Issues..
    # bandit, python specific
    # choose a tool: Criterias: Adoption (Large Community), Complexity, Documentation
    # use multiple tools for the same job
  sast_scan:
      name: Run Bandit Scan
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
        
        - name: Install python 3.8 in ubunutu machine
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        
        - name: Install Bandit
          run: pip install bandit
        
        - name: Run Bandit Scan
          run: bandit -r -ll -ii -o bandit-report.json -f json . # Scans everything in current folder recursively!
          # Will later be consumed by defectdojo a vulnerability management tool

        - name: Upload artifact
          uses: actions/upload-artifact@v3
          if: always() #always executes this steps even when everything else fails!
          with:
            name: bandit-findings
            path: bandit-report.json
          
  # Build Docker Image
  # Scanning Docker Images
  # Docker Scout
  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@v1
        with:
          docker-version: '20.10.7'
      
      - name: Build Docker Image
        run: docker build -f Dockerfile -t myapp:latest .
      
      - name: Docker Scout Scan
        run: | # makes it possible to run various shell commands
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          docker scout quickview
          docker scout cves
