name: CI

on:
  [push] # triggers pipeline when a push is made do any branch in this repo
  #push: triggers when there is a push in a here specified branch
  #  branches:
  #   - main
jobs:
    # SAST drop/scan
    # bandit, python specific
    # choose a tool: Criterias: Adoption (Large Community), Complexity, Documentation
    # use multiple tools for the same job
  sast_scan:
      name: Run Bandit Scan
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
        
        - name: Install python 3.8 in ubunutu machine
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        
        - name: Install Bandit
          run: pip install bandit
        
        - name: Run Bandit Scan
          run: bandit -r -ll -ii -o bandit-report.json -f json . # Scans everything in current folder recursively!